let strip = neopixel.create(DigitalPin.P8, 5, NeoPixelMode.RGB)
basic.showIcon(IconNames.Yes)
basic.forever(function () {
    strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Yellow))
    strip.setPixelColor(2, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(3, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(4, neopixel.colors(NeoPixelColors.Purple))
    strip.show()
    basic.showIcon(IconNames.Happy)
})
